### ISSUE TITLE
Vagrant config for jenkins

### ISSUE THREAD

**Issue by elliott-davis** [misheska/basebox-packer#12]
In the spirit of eating ones own dog food, do you happen to have Jenkins running in vagrant?  If so, would you be opposed to publishing the vagrant configs for it?

**Comment by misheska** [comment]
No I don't have the Jenkins running in vagrant.  The challenge is that there isn't a good way of running a hypervisor within a hypervisor (most 64-bit OSes will refuse to boot up in a "nested hypervisor scenario").  So I have to use physical machine instead.

I've also discovered that while it is possible to run two different hypervisors at once on the same box (like VMware and VirtualBox), it doesn't tend to be a very stable when you try to build a lot of boxes at once, like I do.  So I have a cluster of about 5 physical machines, plus a VM running Razor, a VM running the Jenkins master server, and a VM acting as a squid proxy to cache the DVD images.  With that, the Jenkins master can dynamically make one of the metal boxes a latent slave by PXE booting an OS with the proper hypervisor via PXE w/Razor, enslave it as a Jenkins build node, and create the box.  So my setup has a lot of moving parts in the automation :-)

That being said, the actual way I build and test boxes is very simple.  When a template changes, I build it on the appropriate hypervisor setup (at least two, one for VMware and another for Virtualbox), with the appropriate make command.  Like for example if the CentOS 5.10 64-bit template changed:
    $ cd basebox-packer
    $ make vmware/centos510.box

And assuming this succeeds, I test the box with something like this (say it's the virtualbox one) - though in my case, it's automated:
    $ cd vmware
    $ vagrant box add centos510 centos510.box
    $ mkdir test_centos510
    $ cd test_centos510
    $ vagrant init centos510
    $ vagrant up
    $ vagrant ssh
    $ ls /vagrant

And if any of those commands fail, I use a command-line tool like scrot to take a screenshot of the system (why I like to have the OS install in GUI mode), and send me a e-mail so I can look at it.

This setup isn't perfect, and I still spend far too much time troubleshooting box configs manually than I should because of packer flakiness, but I've been able to automate things more with packer than I was ever able to do with veewee, so it's an improvement in that sense - the tools now are still just too darn primitive ;-)

**Comment by elliott-davis** [comment]
would you be willing to patch and add your jenkins config to the repo (or perhaps just send me a copy).  I am interested in getting a similar setup with Bamboo. I think I can just import a Jenkins config and bamboo will take it and run with it.

**Comment by misheska** [comment]
This is a decent example (though Puppet-based, but easily converted to Chef): http://www.morethanseven.net/2014/01/01/testing-packer-created-images-with-serverspec/
