### ISSUE TITLE
Possibility of Net Installs

### ISSUE THREAD

**Issue by elliott-davis** [misheska/basebox-packer#8]
Would it be acceptable to patch and use the net installs as opposed to the DVD installs.  I've found its generally faster to get the net iso and let the fastest mirror work its magic.  I didn't want to make a pull request if there was a reason you're using DVD iso's though.

**Comment by misheska** [comment]
Of course.  My default use is a little different, in most cases I want the images to start with the original package versions off the install media (no updates) as downgrading can be difficult in some cases and I don't want to use the fastest mirror as that is usually not the fastest for me where I'm creating images, and the fastest mirror plugin can cause more issues for me than it fixes ;-)  (I've got a proxy caching all the DVD installs locally).

I would consider accepting some separate netinstall template variants, if you're talking about a pull request.  Otherwise at some point, I'll create some netinstall variants myself.  I agree that for casual end-user using netinstalls and a fast mirror can be a whole lot faster than downloading a DVD image.

But making my templates netinstalls for the most part is just a matter of changing the iso line and the checksum, so not that big of a deal to have your own variant.  I don't believe I committed the variants I use some places that explicitly turn off the fastest mirror plugin.

**Comment by elliott-davis** [comment]
Ah yes, caching the DVD iso's locally would definitely fix the slowness I was bumping into.  If I were to create some separate templates in a PR, how would you like them to be structured?  I don't mind doing the leg work to write the ks files etc.  I just want to make sure its in an acceptable format/structure before I submit it.

**Comment by misheska** [comment]
If it's not possible to make a conditional to make a template/script work in both the DVD/netinstall scenarios, I would say to just tack on "-netboot" to the netinstall variant of the file (in the same fashion of the Veewee templates).

For example, the ubuntu template dir is structured like so:

centos
├── centos5.10-i386.json
├── centos5.10-x86_64.json
├── centos5.9-i386.json
├── centos5.9-x86_64.json
├── centos6.4-i386.json
├── centos6.4-x86_64.json
├── http
│   └── ks.cfg
└── script
    ├── base.sh
    ├── cleanup.sh
    ├── vagrant.sh
    ├── vmtools.sh
    └── zerodisk.sh

Say you wanted to make a netinstall variant for the 64-bit version of 5.10, a good start would be to create a netinstall template variant named:
    centos5.10-x86_64-netboot.json
Place that alongside all the other .json templates

And then if you need to edit the kickstart, create a similar variant alongside the other one (and modify your .json template so it points at this version):
    http/ks-netboot.cfg

You shouldn't have to modify any of the scripts to get them to work in netinstall scenarios.

You might have noticed that I'm reorganizing the template tree so each os flavor has it's own tree as above, and I still need to finish up the windows & osx subtrees.  For now, you have to build templates by hand and not use the Makefile.  I will be modifying the Makefile after I'm done with the restructuring so that can be used in the future.  If you adhere to the above structure, then the netinstall template will automatically work with the upcoming new Makefile.

**Comment by elliott-davis** [comment]
Closing this in favor or PR comments.
